package dev.s24.fluidlauncher;

import android.animation.TimeInterpolator;import android.content.*;import android.graphics.*;import android.graphics.drawable.Drawable;import android.os.*;import android.view.*;import android.view.animation.DecelerateInterpolator;import android.widget.*;import java.util.*;

/** Allocation-conscious, hardware-accelerated foreground renderer over an untouched system wallpaper. */
public final class LauncherView extends View {
    private static final int COLS=4,ROWS=6; private final Paint paint=new Paint(3),shadow=new Paint(3),label=new Paint(3); private final Rect iconRect=new Rect();
    private List<AppRepository.App> apps=List.of();private final LayoutStore store;private List<LayoutStore.Placement> placements;private TransitionConfig cfg;
    private int page=0,pages;private float downX,downY,lastX,progress,velocity,settleTarget,drawerScroll,drawerVelocity;private long downTime,lastNanos;private boolean tracking,settling,drawer;
    private final VelocityTracker tracker=VelocityTracker.obtain();private final TimeInterpolator ease=new DecelerateInterpolator();private long frames,statsStart=System.nanoTime();private float fps,frameMs;
    public LauncherView(Context c){super(c);setLayerType(View.LAYER_TYPE_HARDWARE,null);setBackgroundColor(Color.TRANSPARENT);store=new LayoutStore(c);placements=store.load();pages=store.pages();cfg=TransitionConfig.load(c,"live");label.setColor(Color.WHITE);label.setTextAlign(Paint.Align.CENTER);label.setTypeface(Typeface.create("sans",Typeface.NORMAL));shadow.setColor(Color.BLACK);setOnLongClickListener(v->{showActions();return true;});setHapticFeedbackEnabled(true);new Thread(()->{List<AppRepository.App> loaded=AppRepository.load(c);post(()->{apps=loaded;seedIfNeeded();invalidate();});},"app-loader").start();}
    public void reloadConfig(){cfg=TransitionConfig.load(getContext(),"live");invalidate();}
    private void seedIfNeeded(){if(!placements.isEmpty())return;ArrayList<LayoutStore.Placement> p=new ArrayList<>();for(int i=0;i<Math.min(apps.size(),COLS*ROWS*pages);i++)p.add(new LayoutStore.Placement(apps.get(i).component().flattenToString(),i/(COLS*ROWS),i%(COLS*ROWS)));placements=p;store.save(p);}
    @Override protected void onDraw(Canvas c){super.onDraw(c);long now=System.nanoTime();long elapsed=lastNanos==0?0:now-lastNanos;float dt=Math.min(.033f,elapsed/1e9f)*(cfg.slowMotion ? .22f : 1f);lastNanos=now;frameMs=elapsed/1e6f;if(drawer)drawDrawer(c,dt);else drawHome(c,dt);updateStats(now);if(settling||Math.abs(drawerVelocity)>.5f)postInvalidateOnAnimation();}
    private void updateStats(long now){frames++;if(now-statsStart>500_000_000L){fps=frames*1e9f/(now-statsStart);frames=0;statsStart=now;}}
    private void drawStats(Canvas c){if(!cfg.fps)return;paint.setColor(0xaa101018);c.drawRoundRect(18,48,230,112,18,18,paint);label.setTextSize(25);label.setTextAlign(Paint.Align.LEFT);c.drawText(String.format(Locale.US,"%.0f FPS  %.2f ms",fps,frameMs),32,89,label);label.setTextAlign(Paint.Align.CENTER);}
    private void drawHome(Canvas c,float dt){if(settling){float displacement=settleTarget-progress;float accel=cfg.springStiffness*displacement-cfg.settlingDamping*velocity;velocity+=accel*dt;progress+=velocity*dt;if(Math.abs(displacement)<.002f&&Math.abs(velocity)<.02f){progress=settleTarget;settling=false;if(settleTarget>=1){page=Math.min(pages-1,page+1);}else if(settleTarget<=-1){page=Math.max(0,page-1);}progress=0;velocity=0;performHapticFeedback(HapticFeedbackConstants.CLOCK_TICK);}}float abs=Math.min(1,Math.abs(progress));int direction=progress>=0?1:-1;drawPage(c,page,progress,false);if(abs>.001f){int other=page+direction;if(other>=0&&other<pages)drawPage(c,other,progress,true);}drawDock(c);drawStats(c);}
    private void drawPage(Canvas c,int targetPage,float p,boolean incoming){float w=getWidth(),top=getPaddingTop()+150,cellW=w/COLS,cellH=(getHeight()-top-210)/ROWS,abs=Math.min(1,Math.abs(p)),dir=p>=0?1:-1;float front=dir>0?w*(1-abs):w*abs;for(LayoutStore.Placement pos:placements){if(pos.page()!=targetPage)continue;AppRepository.App app=find(pos.component());if(app==null)continue;int col=pos.cell()%COLS,row=pos.cell()/COLS;float x=(col+.5f)*cellW,y=top+(row+.5f)*cellH;float dx=(x-front)/Math.max(1,w*cfg.waveWidth);float vertical=(y-downY)/Math.max(1,getHeight()*cfg.verticalSpread);float gaussian=(float)Math.exp(-(dx*dx+vertical*vertical*.36f)*3.2f);float ripple=(float)Math.cos(dx*Math.PI*2/Math.max(.08f,cfg.wavelength));float wave=gaussian*(.72f+.28f*ripple)*cfg.waveAmplitude*cfg.intensity;float reveal=incoming?smooth((abs-cfg.incomingTiming)/(1-cfg.incomingTiming)):smooth(1-abs/Math.max(.05f,cfg.outgoingTiming));if(reveal<=.01f)continue;float travel=(incoming?(dir>0?w:-w)*(1-abs):(dir>0?-w:w)*abs);float px=x+travel+dir*wave*w*cfg.horizontalDisplacement;float z=Math.max(0,wave)*cfg.zElevation;float tilt=-dir*wave*cfg.tilt;drawIcon(c,app,px,y+vertical*wave*5,z,tilt,reveal,wave);}}
    private static float smooth(float x){x=Math.max(0,Math.min(1,x));return x*x*(3-2*x);}
    private void drawIcon(Canvas c,AppRepository.App app,float x,float y,float z,float tilt,float alpha,float bend){float size=getWidth()*.155f;float scale=(1+z/700f)*(1-Math.abs(tilt)/500f);c.save();c.translate(x,y-z*.18f);c.rotate(tilt);c.scale(scale,scale*(1-bend*cfg.meshDeformation*.06f));shadow.setColor(Color.argb((int)(255*cfg.shadowOpacity*alpha),0,0,0));shadow.setShadowLayer(cfg.shadowSoftness+z*.35f,cfg.shadowOffset*.25f+z*.12f,cfg.shadowOffset*.45f+z*.22f,shadow.getColor());c.drawRoundRect(-size*.42f,-size*.38f,size*.42f,size*.46f,size*.25f,size*.25f,shadow);shadow.clearShadowLayer();Drawable d=app.icon();iconRect.set((int)(-size/2),(int)(-size/2),(int)(size/2),(int)(size/2));d.setBounds(iconRect);d.setAlpha((int)(255*alpha));d.draw(c);d.setAlpha(255);label.setTextSize(getWidth()*.032f);label.setAlpha((int)(255*alpha));c.drawText(ellipsize(app.label(),13),0,size*.77f,label);label.setAlpha(255);c.restore();}
    private void drawDock(Canvas c){paint.setColor(0x8820202d);float h=getHeight();c.drawRoundRect(24,h-178,getWidth()-24,h-42,48,48,paint);label.setTextSize(34);c.drawText("⌃  Apps",getWidth()/2f,h-92,label);}
    private void drawDrawer(Canvas c,float dt){drawerScroll+=drawerVelocity*dt;drawerVelocity*=(float)Math.pow(.035,dt);float top=145,cellW=getWidth()/COLS,cellH=165,max=Math.max(0,(float)Math.ceil(apps.size()/(float)COLS)*cellH-(getHeight()-top));drawerScroll=Math.max(0,Math.min(max,drawerScroll));paint.setColor(0xf0141420);c.drawRect(0,0,getWidth(),getHeight(),paint);label.setTextSize(42);c.drawText("Applications",getWidth()/2f,85,label);for(int i=0;i<apps.size();i++){int row=i/COLS,col=i%COLS;float y=top+row*cellH-drawerScroll+70;if(y<-120||y>getHeight()+120)continue;float norm=(y-getHeight()/2f)/(getHeight()/2f);float edge=norm*norm;float scale=1-edge*cfg.drawerEdgeScale;float z=edge*cfg.drawerDepth;drawIcon(c,apps.get(i),(col+.5f)*cellW,y+norm*z,z,norm*cfg.drawerEdgeRotation,scale,0);}drawStats(c);}
    private AppRepository.App find(String component){for(AppRepository.App a:apps)if(a.component().flattenToString().equals(component))return a;return null;}
    private String ellipsize(String s,int n){return s.length()>n?s.substring(0,n-1)+"…":s;}
    @Override public boolean onTouchEvent(android.view.MotionEvent e){tracker.addMovement(e);float x=e.getX(),y=e.getY();switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN-> {tracking=true;settling=false;downX=lastX=x;downY=y;downTime=System.currentTimeMillis();velocity=0;return true;}case MotionEvent.ACTION_MOVE->{if(drawer){float dy=y-downY;drawerScroll-=dy;downY=y;invalidate();}else{float dx=x-downX;if(Math.abs(dx)>12){progress=-dx/getWidth();if((page==0&&progress<0)||(page==pages-1&&progress>0))progress*=.18f;lastX=x;invalidate();}}return true;}case MotionEvent.ACTION_UP,MotionEvent.ACTION_CANCEL->{tracking=false;tracker.computeCurrentVelocity(1000);if(drawer){drawerVelocity=-tracker.getYVelocity();if(Math.abs(x-downX)<20&&Math.abs(y-downY)<20)launchDrawerAt(x,y);postInvalidateOnAnimation();}else{float vx=-tracker.getXVelocity();velocity=vx/getWidth();boolean go=Math.abs(progress)>cfg.gestureThreshold||Math.abs(vx)>cfg.flingSensitivity;settleTarget=go?Math.signum(progress==0?vx:progress):0;if(settleTarget>0&&page>=pages-1||settleTarget<0&&page<=0)settleTarget=0;settling=true;if(System.currentTimeMillis()-downTime>550&&Math.abs(x-downX)<18){performLongClick();}else if(Math.abs(x-downX)<20&&y>getHeight()-220){drawer=true;settling=false;invalidate();}else if(Math.abs(x-downX)<18&&Math.abs(y-downY)<18)launchHomeAt(x,y);}tracker.clear();postInvalidateOnAnimation();return true;}}return true;}
    private void launchHomeAt(float x,float y){float top=getPaddingTop()+150,cellW=getWidth()/(float)COLS,cellH=(getHeight()-top-210)/(float)ROWS;int col=(int)(x/cellW),row=(int)((y-top)/cellH);int cell=row*COLS+col;for(LayoutStore.Placement p:placements)if(p.page()==page&&p.cell()==cell){AppRepository.App a=find(p.component());if(a!=null)AppRepository.launch(getContext(),a);}}
    private void launchDrawerAt(float x,float y){float top=145,cellW=getWidth()/(float)COLS,cellH=165;int col=(int)(x/cellW),row=(int)((y-top+drawerScroll)/cellH),i=row*COLS+col;if(i>=0&&i<apps.size())AppRepository.launch(getContext(),apps.get(i));}
    private void showActions(){PopupMenu menu=new PopupMenu(getContext(),this);menu.getMenu().add("Open app drawer");menu.getMenu().add("Add home page");menu.getMenu().add("Remove last page");menu.getMenu().add("Fluid settings");menu.setOnMenuItemClickListener(i->{String s=i.getTitle().toString();if(s.startsWith("Open")){drawer=true;invalidate();}else if(s.startsWith("Add")){pages++;store.pages(pages);}else if(s.startsWith("Remove")&&pages>1){pages--;page=Math.min(page,pages-1);store.pages(pages);placements.removeIf(p->p.page()>=pages);store.save(placements);invalidate();}else if(s.startsWith("Fluid"))((MainActivity)getContext()).openSettings();return true;});menu.show();}
}
