package dev.s24.fluidlauncher;

import android.app.*;import android.os.*;import android.graphics.Color;import android.view.*;import android.widget.*;

public final class SettingsActivity extends Activity {
    private TransitionConfig config; private LinearLayout controls;
    @Override public void onCreate(Bundle b){super.onCreate(b);rebuild();}
    private TextView text(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(sp);v.setPadding(28,18,20,8);return v;}
    private void rebuild(){config=TransitionConfig.load(this,"live");ScrollView scroll=new ScrollView(this);controls=new LinearLayout(this);controls.setOrientation(LinearLayout.VERTICAL);controls.setPadding(16,48,16,80);controls.setBackgroundColor(Color.rgb(14,14,24));controls.addView(text("Fluid Home • Live laboratory",24));controls.addView(text("Changes are persisted immediately and applied when Home resumes.",14));float[] values=config.values();for(int i=0;i<values.length;i++){final int n=i;TextView label=text(TransitionConfig.NAMES[i]+"  "+String.format("%.2f",values[i]),15);controls.addView(label);SeekBar bar=new SeekBar(this);bar.setMax(1000);bar.setProgress(Math.round(values[i]/config.max(i)*1000));bar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int p,boolean user){if(user){float value=p/1000f*config.max(n);config.set(n,value);label.setText(TransitionConfig.NAMES[n]+"  "+String.format("%.2f",value));config.save(SettingsActivity.this,"live");}}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});controls.addView(bar);}
        Switch fps=new Switch(this);fps.setText("FPS and frame-time overlay");fps.setTextColor(Color.WHITE);fps.setChecked(config.fps);fps.setOnCheckedChangeListener((b,v)->{config.fps=v;config.save(this,"live");});controls.addView(fps);Switch slow=new Switch(this);slow.setText("Slow-motion debug animation");slow.setTextColor(Color.WHITE);slow.setChecked(config.slowMotion);slow.setOnCheckedChangeListener((b,v)->{config.slowMotion=v;config.save(this,"live");});controls.addView(slow);
        LinearLayout buttons=new LinearLayout(this);String[] names={"Restore defaults","Save preset","Load preset"};for(String name:names){Button button=new Button(this);button.setText(name);button.setOnClickListener(v->{if(name.startsWith("Restore")){new TransitionConfig().save(this,"live");rebuild();}else if(name.startsWith("Save")){config.save(this,"preset");Toast.makeText(this,"Preset saved",Toast.LENGTH_SHORT).show();}else{TransitionConfig.load(this,"preset").save(this,"live");rebuild();}});buttons.addView(button,new LinearLayout.LayoutParams(0,-2,1));}controls.addView(buttons);scroll.addView(controls);setContentView(scroll);}
}
